/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

// Stats provides the overall progress of the scan all process.
type Stats struct {
	// The total number of scan processes triggered by the scan all action
	Total int32 `json:"total,omitempty"`
	// The number of the finished scan processes triggered by the scan all action
	Completed int32 `json:"completed,omitempty"`
	// The requester identity which usually uses the ID of the scan all job
	Requester string `json:"requester,omitempty"`
	// The metrics data for the each status
	Metrics map[string]int32 `json:"metrics,omitempty"`
}
