/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package harbor

type IsDefault struct {
	// A flag indicating whether a scanner registration is default.
	IsDefault bool `json:"is_default,omitempty"`
}
