/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

// retention selector
type RetentionSelectorMetadata struct {
	DisplayText string `json:"display_text,omitempty"`
	Kind string `json:"kind,omitempty"`
	Decorations []string `json:"decorations,omitempty"`
}
