/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package harbor

// rule param
type RetentionRuleParamMetadata struct {
	Type_ string `json:"type,omitempty"`
	Unit string `json:"unit,omitempty"`
	Required bool `json:"required,omitempty"`
}
