/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

// retention policy
type RetentionPolicy struct {
	Id int64 `json:"id,omitempty"`
	Algorithm string `json:"algorithm,omitempty"`
	Rules []RetentionRule `json:"rules,omitempty"`
	Trigger *RetentionRuleTrigger `json:"trigger,omitempty"`
	Scope *RetentionPolicyScope `json:"scope,omitempty"`
}
