/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package harbor

type RetentionPolicyScope struct {
	Level string `json:"level,omitempty"`
	Ref int32 `json:"ref,omitempty"`
}
