/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

type AdminJobScheduleObj struct {
	// The schedule type. The valid values are 'Hourly', 'Daily', 'Weekly', 'Custom', 'Manually' and 'None'. 'Manually' means to trigger it right away and 'None' means to cancel the schedule. 
	Type_ string `json:"type,omitempty"`
	// A cron expression, a time-based job scheduler.
	Cron string `json:"cron,omitempty"`
}
