/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

// the tag retention rule metadata
type RetentionRuleMetadata struct {
	// rule id
	RuleTemplate string `json:"rule_template,omitempty"`
	// rule display text
	DisplayText string `json:"display_text,omitempty"`
	// rule action
	Action string `json:"action,omitempty"`
	// rule params
	Params []RetentionRuleParamMetadata `json:"params,omitempty"`
}
