/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

type ConfigurationsResponse struct {
	AuthMode *StringConfigItem `json:"auth_mode,omitempty"`
	CountPerProject *IntegerConfigItem `json:"count_per_project,omitempty"`
	EmailFrom *StringConfigItem `json:"email_from,omitempty"`
	EmailHost *StringConfigItem `json:"email_host,omitempty"`
	EmailPort *IntegerConfigItem `json:"email_port,omitempty"`
	EmailIdentity *StringConfigItem `json:"email_identity,omitempty"`
	EmailUsername *StringConfigItem `json:"email_username,omitempty"`
	EmailSsl *BoolConfigItem `json:"email_ssl,omitempty"`
	EmailInsecure *BoolConfigItem `json:"email_insecure,omitempty"`
	LdapUrl *StringConfigItem `json:"ldap_url,omitempty"`
	LdapBaseDn *StringConfigItem `json:"ldap_base_dn,omitempty"`
	LdapFilter *StringConfigItem `json:"ldap_filter,omitempty"`
	// 0-LDAP_SCOPE_BASE, 1-LDAP_SCOPE_ONELEVEL, 2-LDAP_SCOPE_SUBTREE
	LdapScope int32 `json:"ldap_scope,omitempty"`
	LdapUid *StringConfigItem `json:"ldap_uid,omitempty"`
	// The DN of the user to do the search.
	LdapSearchDn string `json:"ldap_search_dn,omitempty"`
	LdapTimeout *IntegerConfigItem `json:"ldap_timeout,omitempty"`
	LdapGroupAttributeName *StringConfigItem `json:"ldap_group_attribute_name,omitempty"`
	LdapGroupBaseDn *StringConfigItem `json:"ldap_group_base_dn,omitempty"`
	LdapGroupSearchFilter *StringConfigItem `json:"ldap_group_search_filter,omitempty"`
	LdapGroupSearchScope *IntegerConfigItem `json:"ldap_group_search_scope,omitempty"`
	LdapGroupAdminDn *StringConfigItem `json:"ldap_group_admin_dn,omitempty"`
	OidcClientId *StringConfigItem `json:"oidc_client_id,omitempty"`
	OidcEndpoint *StringConfigItem `json:"oidc_endpoint,omitempty"`
	OidcName *StringConfigItem `json:"oidc_name,omitempty"`
	OidcScope *StringConfigItem `json:"oidc_scope,omitempty"`
	OidcVerifyCert *BoolConfigItem `json:"oidc_verify_cert,omitempty"`
	ProjectCreationRestriction *StringConfigItem `json:"project_creation_restriction,omitempty"`
	QuotaPerProjectEnable *BoolConfigItem `json:"quota_per_project_enable,omitempty"`
	ReadOnly *BoolConfigItem `json:"read_only,omitempty"`
	SelfRegistration *BoolConfigItem `json:"self_registration,omitempty"`
	StoragePerProject *IntegerConfigItem `json:"storage_per_project,omitempty"`
	TokenExpiration *IntegerConfigItem `json:"token_expiration,omitempty"`
	VerifyRemoteCert *BoolConfigItem `json:"verify_remote_cert,omitempty"`
	ScanAllPolicy *ConfigurationsScanAllPolicy `json:"scan_all_policy,omitempty"`
}
