/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package harbor

type ProjectScanner struct {
	// The identifier of the scanner registration
	Uuid string `json:"uuid,omitempty"`
}
