/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package harbor

// The webhook policy target object.
type WebhookTargetObject struct {
	// The webhook target notify type.
	Type_ string `json:"type,omitempty"`
	// The webhook target address.
	Address string `json:"address,omitempty"`
	// The webhook auth header.
	AuthHeader string `json:"auth_header,omitempty"`
	// Whether or not to skip cert verify.
	SkipCertVerify bool `json:"skip_cert_verify,omitempty"`
}
