/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

type UserSearch struct {
	// The ID of the user.
	UserId int32 `json:"user_id,omitempty"`
	Username string `json:"username,omitempty"`
}
