/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

// The system health status
type OverallHealthStatus struct {
	// The overall health status. It is \"healthy\" only when all the components' status are \"healthy\"
	Status string `json:"status,omitempty"`
	Components []ComponentHealthStatus `json:"components,omitempty"`
}
