/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

type Scanner struct {
	// Name of the scanner
	Name string `json:"name,omitempty"`
	// Name of the scanner provider
	Vendor string `json:"vendor,omitempty"`
	// Version of the scanner adapter
	Version string `json:"version,omitempty"`
}
