/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package harbor

type RetentionExecutionTask struct {
	Id int64 `json:"id,omitempty"`
	ExecutionId int64 `json:"execution_id,omitempty"`
	Repository string `json:"repository,omitempty"`
	JobId string `json:"job_id,omitempty"`
	Status string `json:"status,omitempty"`
	StatusCode int32 `json:"status_code,omitempty"`
	StatusRevision int64 `json:"status_revision,omitempty"`
	StartTime string `json:"start_time,omitempty"`
	EndTime string `json:"end_time,omitempty"`
	Total int32 `json:"total,omitempty"`
	Retained int32 `json:"retained,omitempty"`
}
