/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

type Body4 struct {
	// The URL of OIDC endpoint to be tested.
	Url string `json:"url,omitempty"`
	// Whether the certificate should be verified
	VerifyCert bool `json:"verify_cert,omitempty"`
}
