/*
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * API version: 1.10.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package github.com/angeiv/harbor

// The webhook job.
type WebhookJob struct {
	// The webhook job ID.
	Id int64 `json:"id,omitempty"`
	// The webhook policy ID.
	PolicyId int64 `json:"policy_id,omitempty"`
	// The webhook job event type.
	EventType string `json:"event_type,omitempty"`
	// The webhook job notify type.
	NotifyType string `json:"notify_type,omitempty"`
	// The webhook job status.
	Status string `json:"status,omitempty"`
	// The webhook job notify detailed data.
	JobDetail string `json:"job_detail,omitempty"`
	// The webhook job creation time.
	CreationTime string `json:"creation_time,omitempty"`
	// The webhook job update time.
	UpdateTime string `json:"update_time,omitempty"`
}
